# Generated by Django 5.1.4 on 2025-01-21 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nom de la catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nom du document')),
                ('photo', models.FileField(upload_to='pdfs/', verbose_name='fichier')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nom de la photo')),
                ('photo', models.ImageField(upload_to='Photos/', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, unique=True, verbose_name='Description du bien')),
                ('rubrique', models.CharField(choices=[('CUISINE', 'Cuisine'), ('SALON', 'Salon'), ('CHAMBREJ', 'Chambre Jérémys'), ('CHAMBREP', 'Chambre Parents'), ('SALLE DE BAIN', 'Salle de bain'), ('WC', 'WC'), ('TERASSENE', 'Terasse Nord Est'), ('TERASSESO', 'Terasse Sud Ouest'), ('Garage', 'Garage'), ('Bijoux', 'Bijoux'), ('AUTRE', 'Autre')], default='Autre', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('achat_at', models.DateTimeField(verbose_name='date achat')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biens.categorie')),
                ('document', models.ManyToManyField(blank=True, related_name='BiensDocs', to='biens.doc')),
                ('photo', models.ManyToManyField(blank=True, related_name='BiensPhotos', to='biens.photo')),
            ],
            options={
                'verbose_name': 'bien',
            },
        ),
    ]
