# Generated by Django 5.1.4 on 2025-02-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nom de la catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nom rubrique')),
                ('montant_assu', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='montant_assurance')),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, unique=True, verbose_name="Description de l'objet")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('achat_at', models.DateField(verbose_name='date achat')),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='montant')),
                ('document', models.FileField(default='pdfs/defaut.pdf', upload_to='pdfs/', verbose_name='document pdf')),
                ('photo', models.ImageField(default='Photos/defaut.jpg', upload_to='Photos/', verbose_name='Photo')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Objet_Categorie', to='biens.categorie')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Objet_Rubrique', to='biens.rubrique')),
            ],
            options={
                'verbose_name': 'objet',
            },
        ),
    ]
