# Generated by Django 5.1.4 on 2025-01-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='photo',
            new_name='fichier',
        ),
    ]
