# Generated by Django 5.1.4 on 2025-02-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objet',
            name='created_user',
        ),
    ]
