# Generated by Django 5.1.4 on 2025-02-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='piece',
            field=models.CharField(choices=[('SALON', 'Salon'), ('CUISINE', 'Cuisine'), ('TERRASSES', 'Terrasses'), ('CHAMBRE_J', 'Chambre Jérémy'), ('CHAMBRE_P', 'Chambre Parents'), ('BUREAU', 'Bureau'), ('GARAGE', 'Garage'), ('AUTRE', 'Autre')], default='Autre', max_length=20, verbose_name='pièce'),
        ),
    ]
