# Generated by Django 5.1.4 on 2025-01-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0002_rename_photo_doc_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='fichier',
            field=models.FileField(default='pdfs/defaut.pdf', upload_to='pdfs/', verbose_name='document pdf'),
        ),
    ]
