# Generated by Django 5.1.4 on 2025-02-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0002_remove_objet_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='piece',
            field=models.CharField(choices=[('Salon', 'Salon'), ('Cuisine', 'Cuisine'), ('Terrasses', 'Terrasses'), ('Chambre_Jérémy', 'Chambre Jérémy'), ('Chambre_Parents', 'Chambre Parents'), ('Bureau', 'Bureau'), ('Garage', 'Garage'), ('Bureau', 'Bureau'), ('Autre', 'Autre')], default='Autre', max_length=20, verbose_name='pièce'),
        ),
    ]
