# Generated by Django 5.1.4 on 2025-02-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0002_objet_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='created_user',
            field=models.CharField(default='admin', max_length=32, verbose_name='utilisateur qui a créé'),
        ),
    ]
