# Generated by Django 5.1.4 on 2025-01-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0003_alter_doc_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='bien',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/'),
        ),
    ]
