# Generated by Django 5.1.4 on 2025-01-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0004_bien_fichier_bien_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='image',
        ),
    ]
