# Generated by Django 5.1.4 on 2025-03-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0005_alter_objet_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='estimation',
            field=models.BooleanField(default=False),
        ),
    ]
