# Generated by Django 5.1.4 on 2025-01-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0005_rename_photo_photo_image_remove_bien_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='achat_at',
            field=models.DateField(verbose_name='date achat'),
        ),
    ]
