# Generated by Django 5.1.4 on 2025-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0006_alter_bien_achat_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='document',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='photo',
        ),
        migrations.AddField(
            model_name='bien',
            name='document',
            field=models.FileField(default='pdfs/defaut.pdf', upload_to='pdfs/', verbose_name='document pdf'),
        ),
        migrations.AddField(
            model_name='bien',
            name='photo',
            field=models.ImageField(default='Photos/defaut.jpg', upload_to='Photos/', verbose_name='Photo'),
        ),
    ]
