# Generated by Django 5.1.4 on 2025-03-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0006_objet_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='estimation',
            field=models.BooleanField(default=False, verbose_name='Montant Estimé'),
        ),
    ]
