# Generated by Django 5.1.4 on 2025-01-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0007_remove_bien_document_remove_bien_photo_bien_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='montant'),
        ),
    ]
