# Generated by Django 5.1.4 on 2025-01-28 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0008_bien_montant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, unique=True, verbose_name="Description de l'objet")),
                ('rubrique', models.CharField(choices=[('CUISINE', 'Cuisine'), ('SALON', 'Salon'), ('CHAMBREJ', 'Chambre Jérémys'), ('CHAMBREP', 'Chambre Parents'), ('SALLE DE BAIN', 'Salle de bain'), ('WC', 'WC'), ('TERASSENE', 'Terasse Nord Est'), ('TERASSESO', 'Terasse Sud Ouest'), ('Garage', 'Garage'), ('Bijoux', 'Bijoux'), ('AUTRE', 'Autre')], default='Autre', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('achat_at', models.DateField(verbose_name='date achat')),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='montant')),
                ('document', models.FileField(default='pdfs/defaut.pdf', upload_to='pdfs/', verbose_name='document pdf')),
                ('photo', models.ImageField(default='Photos/defaut.jpg', upload_to='Photos/', verbose_name='Photo')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biens.categorie')),
            ],
            options={
                'verbose_name': 'objet',
            },
        ),
        migrations.DeleteModel(
            name='Bien',
        ),
    ]
