# version: "3"
services:
  # Serveur web Django

  # Base de donnée Postgres
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bd_ged
      - POSTGRES_USER=angel
      - POSTGRES_PASSWORD=angel
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    ports:
      - "8000:8000"
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --bind 0.0.0.0:8000 ged.wsgi:application
    volumes:
      - .:/app
    environment:
      - PG_USER=angel
      - PG_PASSWORD=angel
      - PG_DB=bd_ged
      - PG_PORT=5432
      - PG_HOST=db
      - DEBUG=False
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web
    
volumes:
  postgres_data:
  static_volume:

  

# adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

