# Generated by Django 5.2 on 2025-04-17 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('temps_preparation', models.IntegerField()),
                ('temps_cuisson', models.IntegerField()),
                ('nombre_couverts', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('etapes', models.TextField()),
                ('conseils', models.TextField(default=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Photos/')),
                ('video_url_youtube', models.URLField(blank=True, unique=True)),
                ('note', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to='recettes.categorie')),
            ],
        ),
    ]
