# Generated by Django 5.2 on 2025-04-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.ImageField(upload_to='')),
                ('unit', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredient_unit',
            field=models.ManyToManyField(blank=True, related_name='recettes', to='recettes.ingredient_unit'),
        ),
    ]
