# Generated by Django 5.2 on 2025-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_ingredient_unit_recette_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_unit',
            name='qte',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
