# Generated by Django 5.2 on 2025-04-25 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0003_alter_ingredient_unit_qte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='ingredient_unit',
        ),
        migrations.CreateModel(
            name='RecetteIngredientUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('ingredient_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.ingredient_unit')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recette_ingredient_units', to='recettes.recette')),
            ],
        ),
    ]
