# Generated by Django 5.2 on 2025-04-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0004_remove_recette_ingredient_unit_recetteingredientunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetteingredientunit',
            name='ingredient_unit',
        ),
        migrations.DeleteModel(
            name='Ingredient_Unit',
        ),
    ]
