# Generated by Django 5.2 on 2025-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0005_remove_recetteingredientunit_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='conseils',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recetteingredientunit',
            name='unit',
            field=models.CharField(choices=[('g', 'Grammes'), ('kg', 'Kilogrammes'), ('l', 'Litres'), ('cl', 'Centilitres'), ('ml', 'Millilitres'), ('u', 'Unité'), ('bouteille', 'Bouteille'), ('cuillère à café', 'Cuillère à café'), ('cuillère à soupe', 'Cuillère à soupe'), ('pincée', 'Pincée'), ('sachet', 'Sachet'), ('boîte', 'Boîte'), ('tasse', 'Tasse'), ('verre', 'Verre'), ('barquette', 'Barquette'), ('bocal', 'Bocal')], max_length=200),
        ),
    ]
