# Generated by Django 5.2 on 2025-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0007_alter_recette_video_url_youtube_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetteingredientunit',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recetteingredientunit',
            name='qte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recetteingredientunit',
            name='unit',
            field=models.CharField(choices=[('', 'Vide'), ('g', 'Grammes'), ('kg', 'Kilogrammes'), ('l', 'Litres'), ('cl', 'Centilitres'), ('ml', 'Millilitres'), ('dl', 'Décilitres'), ('feuille/s', 'Feuille'), ('branche/s', 'Branche'), ('tranche/s', 'Tranche'), ('citron/s', 'Citron'), ('gousse/s', 'Gousse'), ('pomme/s', 'Pomme'), ('orange/s', 'Orange'), ('banane/s', 'Banane'), ('carotte/s', 'Carotte'), ('tomate/s', 'Tomate'), ('oignon/s', 'Oignon'), ('ail/s', 'Ail'), ('bouteille/s', 'Bouteille'), ('cuillère/s à café', 'Cuillère à café'), ('cuillère/s à soupe', 'Cuillère à soupe'), ('pincée/s', 'Pincée'), ('tour/s de moulin', 'Tour de moulin'), ('poignée/s', 'Poignée'), ('sachet/s', 'Sachet'), ('sachets/s', 'Sachets'), ('barre/s', 'Barre'), ('barres/s', 'Barres'), ('pot/s', 'Pot'), ('pots/s', 'Pots'), ('boîte/s de conserve', 'Boîte de conserve'), ('brique/s', 'Brique'), ('briques/s', 'Briques'), ('sachet', 'Sachet'), ('boîte/s', 'Boîte'), ('tasse/s', 'Tasse'), ('verre/s', 'Verre'), ('barquette/s', 'Barquette'), ('bocal/s', 'Bocal')], max_length=200),
        ),
    ]
