# Generated by Django 5.2 on 2025-05-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0008_alter_recetteingredientunit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetteingredientunit',
            name='qte',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recetteingredientunit',
            name='unit',
            field=models.CharField(choices=[('g', 'Grammes'), ('kg', 'Kilogrammes'), ('l', 'Litres'), ('cl', 'Centilitres'), ('ml', 'Millilitres'), ('dl', 'Décilitres'), ('sel', 'Sel'), ('poivre', 'Poivre'), ('feuille/s', 'Feuille'), ('branche/s', 'Branche'), ('tranche/s', 'Tranche'), ('citron/s', 'Citron'), ('gousse/s', 'Gousse'), ('pomme/s', 'Pomme'), ('orange/s', 'Orange'), ('banane/s', 'Banane'), ('carotte/s', 'Carotte'), ('tomate/s', 'Tomate'), ('oignon/s', 'Oignon'), ('ail/s', 'Ail'), ('bouteille/s', 'Bouteille'), ('cuillère/s à café', 'Cuillère à café'), ('cuillère/s à soupe', 'Cuillère à soupe'), ('pincée/s', 'Pincée'), ('tour/s de moulin', 'Tour de moulin'), ('morceau/x', 'Morceau'), ('poignée/s', 'Poignée'), ('sachet/s', 'Sachet'), ('sachets/s', 'Sachets'), ('barre/s', 'Barre'), ('barres/s', 'Barres'), ('pot/s', 'Pot'), ('pots/s', 'Pots'), ('boîte/s de conserve', 'Boîte de conserve'), ('brique/s', 'Brique'), ('briques/s', 'Briques'), ('sachet', 'Sachet'), ('boîte/s', 'Boîte'), ('tasse/s', 'Tasse'), ('verre/s', 'Verre'), ('barquette/s', 'Barquette'), ('bocal/s', 'Bocal')], max_length=200),
        ),
    ]
