# Generated by Django 5.2 on 2025-05-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0009_alter_recetteingredientunit_qte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetteingredientunit',
            name='qte',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
