# Generated by Django 5.1.4 on 2025-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien', models.CharField(max_length=96, unique=True, verbose_name='description')),
                ('rubrique', models.CharField(choices=[('SALON', 'Salon'), ('CUISINE', 'Cuisine'), ('BUREAU', 'Bureau'), ('CHAMBRE', 'Chambre'), ('SALLEDEBAIN', 'Salle de bain'), ('JARDIN', 'Jardin'), ('GARAGE', 'Garage'), ('CAVE', 'Cave'), ('AUTRE', 'Autre')], default='SALON', max_length=15)),
                ('created_achat', models.DateTimeField(auto_now_add=True, verbose_name='date achat')),
            ],
            options={
                'verbose_name': 'document',
            },
        ),
    ]
