# Generated by Django 5.1.4 on 2025-01-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_achat',
            field=models.DateTimeField(verbose_name='date achat'),
        ),
    ]
