# Generated by Django 5.1.4 on 2025-01-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_created_achat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='bien',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_achat',
        ),
    ]
