# Generated by Django 5.1.4 on 2025-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_bien_document_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rubrique',
            field=models.CharField(choices=[('BS', 'Bulletin de salaire'), ('Retraite', 'Attestation de paiement de retraite'), ('Impôts', "déclaration d'impôts"), ('AUTRE', 'Autre')], default='Retraite', max_length=15),
        ),
    ]
