# Generated by Django 5.1.4 on 2025-01-21 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_rubrique'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Mois_année',
            field=models.DateField(default=datetime.date.today, verbose_name='mois et année'),
        ),
        migrations.AlterField(
            model_name='document',
            name='rubrique',
            field=models.CharField(choices=[('BS', 'Bulletin de salaire'), ('Retraite', 'Attestation de paiement de retraite'), ('Impôts', "Déclaration d'impôts"), ('AUTRE', 'Autre')], default='Retraite', max_length=15),
        ),
    ]
