# Generated by Django 5.1.4 on 2025-01-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_mois_année_alter_document_rubrique'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Document_pdf',
            field=models.FileField(default='pdfs/defaut.pdf', upload_to='pdfs/', verbose_name='document pdf'),
        ),
    ]
