# Generated by Django 5.1.4 on 2025-01-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_document_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='Mois_année',
        ),
        migrations.AddField(
            model_name='document',
            name='annee',
            field=models.IntegerField(default=2025, verbose_name='année'),
        ),
        migrations.AddField(
            model_name='document',
            name='mois',
            field=models.IntegerField(default=1, verbose_name='mois'),
        ),
    ]
