# Generated by Django 5.1.4 on 2025-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_document_mois_année_document_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='mois',
            field=models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default='January', max_length=9, verbose_name='mois'),
        ),
    ]
