# Generated by Django 5.1.4 on 2025-01-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_document_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='commentaire'),
        ),
    ]
