# Generated by Django 5.1.4 on 2025-03-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(default='url'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mois',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default='3', verbose_name='mois'),
        ),
    ]
