# Generated by Django 5.1.4 on 2025-03-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_url_alter_document_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rubrique',
            field=models.CharField(choices=[('BS', 'Bulletin de salaire'), ('Retraite', 'Attestation de paiement de retraite'), ('Impôts', "Déclaration d'impôts"), ('Autre', 'Autre')], default='Autre', max_length=15),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(default='https://absite.fr'),
        ),
    ]
