# Generated by Django 5.1.4 on 2025-03-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_document_rubrique_alter_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(default='https://absite.fr', verbose_name='Lien vers document sur le Cloud'),
        ),
    ]
