# Generated by Django 5.1.4 on 2025-03-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_alter_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_pdf',
            field=models.FileField(default='pdfs_doc/defaut.pdf', upload_to='pdfs_doc/', verbose_name='document pdf'),
        ),
        migrations.AlterField(
            model_name='document',
            name='rubrique',
            field=models.CharField(choices=[('Doc. Notaire', 'Documents Notaire'), ('Doc. Banque', 'Documents de la Banque'), ('Doc. Epargne', 'Doc. Epargne'), ('Factures', 'Factures'), ('BS', 'Bulletin de salaire'), ('Retraite', 'Attestation de paiement de retraite'), ('Impôts', "Déclaration d'impôts"), ('Autre', 'Autre')], default='Autre', max_length=15),
        ),
    ]
