# Generated by Django 5.1.4 on 2025-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_alter_document_document_pdf_alter_document_rubrique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rubrique',
            field=models.CharField(choices=[('Taxe Foncière', 'Taxe Foncière'), ('Avis Imposition', "Avis d'Imposition"), ('Décl. revenus', 'Déclarations de revenus'), ('Militaire', 'Attestation des services accomplis'), ('Logement', 'Logement - Propriété'), ('Banque', 'Banque'), ('Véhicule', 'Véhicule'), ('Consommation', 'Consommation - Apparail Ménager'), ('Famille', 'Famille'), ('Factures', 'Factures'), ('BS', 'Bulletin de salaire'), ('Travail', 'Contrat de travail'), ('Sld tout compte', 'Solde de tout compte'), ('Retraite', 'Retraite - Titre de pension'), ('Assurance', 'Assurance'), ('Santé', 'Santé'), ('Autre', 'Autre')], default='Autre', max_length=15),
        ),
    ]
