# Generated by Django 5.1.4 on 2025-03-25 14:54

import django.db.models.deletion
import django.utils.timezone
import papiers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Type de document')),
                ('duree_conservation', models.IntegerField(default=5, verbose_name='Durée de conservation en Année')),
                ('permanente', models.BooleanField(default=False, verbose_name='Durée permanente')),
                ('precision', models.TextField(blank=True, verbose_name='précision')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=96, unique=True, verbose_name='description')),
                ('rubrique', models.CharField(choices=[('Assurance', 'Assurance'), ('Véhicule', 'Véhicule-Voiture-Vélo'), ('Banque', 'Banque'), ('Consommation', 'Consommation-Appareil ménager'), ('Famille', 'Famille-Scolarité'), ('Logement', 'Logement'), ('Impôts', 'Impôts et taxes'), ('Retraite', 'Retraite-Travail-Chômage'), ('Militaires', 'Papiers militaires'), ('Employeur', 'Employeur'), ('Santé', 'Santé'), ('Décès', 'Décès')], default='Autre', max_length=15)),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=papiers.models.get_current_month, verbose_name='mois')),
                ('annee', models.IntegerField(default=papiers.models.get_current_year, verbose_name='année')),
                ('date_reference', models.DateField(default=django.utils.timezone.now, verbose_name='date de référence')),
                ('Document_pdf', models.FileField(default='pdfs_doc/defaut.pdf', upload_to='pdfs_doc/', verbose_name='document pdf')),
                ('url', models.URLField(default='https://absite.fr', verbose_name='Lien vers document sur le Cloud')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('type_document', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Document_TypeDocument', to='papiers.typedocument')),
            ],
            options={
                'verbose_name': 'document',
            },
        ),
    ]
